package constant

var category = []string{
	"Array",
	"String",
	"Hash Table",
	"Two Pointers",
	"Sliding Window",
	"Binary Search",
	"Sorting",
	"Stack",
	"Queue",
	"Linked List",
	"Tree",
	"Binary Tree",
	"Binary Search Tree",
	"Heap / Priority Queue",
	"Graph",
	"DFS",
	"BFS",
	"Backtracking",
	"Dynamic Programming",
	"Greedy",
	"Math",
	"Bit Manipulation",
	"Prefix Sum",
	"Union-Find (Disjoint Set)",
	"Recursion",
	"Trie",
	"Segment Tree",
	"Fenwick Tree (Binary Indexed Tree)",
	"Matrix",
	"Geometry",
	"Number Theory",
	"String Matching (KMP / Z-function)",
	"Topological Sort",
	"Shortest Path (Dijkstra/Bellman-Ford)",
	"Minimum Spanning Tree (Kruskal/Prim)",
	"Game Theory",
}
var Difficult = map[string]string{
	"EASY":   "easy",
	"MEDIUM": "medium",
	"HARD":   "hard",
}
